name: artic-test
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - artic-porechop
  - artic-tools
  - bcftools
  - biopython
  - bwa
  - clint
  - htslib
  - longshot>=0.4.3
  - medaka=1.6.1
  - minimap2
  - multiqc
  - muscle=3.8
  - nanopolish
  - nomkl
  - pandas
  - pip
  - pysam
  - pytest
  - python
  - pyvcf
  - samtools
  - tqdm
